fixed narrowing conversion error
explicit cast to int is neede here to avoid gcc c++0x compilation
error: narrowing conversion of ‘M’ from ‘vigra::MultiArrayIndex’ to ‘int’ inside { }

int overflow should not occur here because PyArray_NDIM returns
an integer which is converted to long in NumpyAnyArray::ndim()

Perhaps one should make NumpyAnyArray consitent and not use MulitArrayIndex
for dimensions but int as it is done in numpy base classes (like PyArray_NDIM).